[main]
layer=top
font=Geist Medium:size=11
prompt="❯ "
icon-theme=Papirus-Dark
width=45
lines=10
horizontal-pad=20
vertical-pad=15
inner-pad=10
line-height=25
letter-spacing=0.2

[colors]
text=#e5e2e4ff
prompt=#c0c5e0ff
input=#e5e2e4ff
match=#c0c5e0ff
selection=#35343680
selection-text=#c0c5e0ff
selection-match=#c0c5e0ff
background=#131315e6
# High-visibility primary border
border=#c0c5e0ff

[border]
radius=40
width=3
