[main]
layer=top
font=Geist Medium:size=11
prompt="❯ "
icon-theme=Papirus-Dark
width=45
lines=10
horizontal-pad=20
vertical-pad=15
inner-pad=10
line-height=25
letter-spacing=0.2

[colors]
text=#e9dfecff
prompt=#d9b9ffff
input=#e9dfecff
match=#d9b9ffff
selection=#38333c80
selection-text=#d9b9ffff
selection-match=#d9b9ffff
background=#16121ae6
# High-visibility primary border
border=#d9b9ffff

[border]
radius=40
width=3
