[main]
font=Geist:weight=bold:size=8
prompt="❯ "
icon-theme=Papirus
width=40
lines=10
horizontal-pad=15
vertical-pad=10
inner-pad=8
line-height=20
letter-spacing=0.5

[border]
width=2
radius=12

[colors]
# The main text color (Apps and list items)
text=#dde4e1ff

# The color of the '❯' prompt specifically
prompt=#82d5c8ff

# The color of the characters you have typed (Searching)
input=#dde4e1ff

# The color of the matched characters in the list
match=#82d5c8ff

# Selection colors (When you hover/highlight an item)
selection=#82d5c844
selection-text=#82d5c8ff
selection-match=#82d5c8ff

background=#0e1513dd
border=00000000

[border]
width=0
radius=12
