timeout: 10
default_entry: 1

# Background Wallpaper & Backdrop
wallpaper: boot():/limine-wallpaper.png
wallpaper_style: stretched
backdrop: 101012

# Interface Branding
interface_branding: Limine 12.9.0
interface_branding_colour: c0c5e0

# Full-Screen Glass Terminal
# In Limine TTRRGGBB format: 'B0' = 70% transparency (frosted glass, wallpaper fully visible through it)
# 'term_margin: 0' ensures the glass covers 100% of the screen from edge to edge
term_background: b0131315
term_foreground: ffffff
term_margin: 0

# Palette & Highlights
term_palette: 131315;ffb4ab;c0c5e0;e5e2e4;c0c5e0;c6c6cd;909097;ffffff
term_palette_bright: 201f21;ffb4ab;c0c5e0;ffffff;c0c5e0;c6c6cd;909097;ffffff

# Boot Entries
/Arch Linux (Zen)
    protocol: linux
    path: boot():/vmlinuz-linux-zen
    cmdline: root=UUID=9ee82268-55c2-4523-9eaa-70f475163f23 rw rootflags=subvol=@ quiet loglevel=3 rd.udev.log_level=3 udev.log_priority=3 vt.global_cursor_default=0 systemd.show_status=auto nowatchdog
    module_path: boot():/initramfs-linux-zen.img

/Arch Linux (LTS)
    protocol: linux
    path: boot():/vmlinuz-linux-lts
    cmdline: root=UUID=9ee82268-55c2-4523-9eaa-70f475163f23 rw rootflags=subvol=@ quiet loglevel=3 rd.udev.log_level=3 udev.log_priority=3 vt.global_cursor_default=0 systemd.show_status=auto nowatchdog
    module_path: boot():/initramfs-linux-lts.img

/Windows 11
    protocol: efi
    path: boot():/EFI/Microsoft/Boot/bootmgfw.efi
