$primary = rgb(c0c5e0)
$on_primary = rgb(2a3044)
$surface = rgb(131315)
$on_surface = rgb(e5e2e4)
$on_surface_variant = rgb(c6c6cd)
$surface_container = rgb(201f21)
$surface_container_highest = rgb(353436)
$outline = rgb(909097)
$error = rgb(ffb4ab)

