$primary = rgb(d9b9ff)
$on_primary = rgb(460085)
$surface = rgb(16121a)
$on_surface = rgb(e9dfec)
$on_surface_variant = rgb(cec2d5)
$surface_container = rgb(221e27)
$surface_container_highest = rgb(38333c)
$outline = rgb(978d9f)
$error = rgb(ffb4ab)

