$primary = rgb(a0ccea)
$on_primary = rgb(00344b)
$surface = rgb(111415)
$on_surface = rgb(e2e2e4)
$on_surface_variant = rgb(c1c7cd)
$surface_container = rgb(1e2022)
$surface_container_highest = rgb(333537)
$outline = rgb(8b9197)
$error = rgb(ffb4ab)

