require("configs.colors")
require("configs.env")
require("configs.monitors")
require("configs.settings")
require("configs.binds")
require("configs.autostart")

hl.config({
    autogenerated = false
})

-- Gestures
hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

-- Window swipe
hl.gesture({
    fingers = 4,
    direction = "left",
    action = function()
        hl.dispatch(hl.dsp.exec_cmd("~/.config/hypr/scripts/layout_navigate.sh focus_right"))
    end
})

hl.gesture({
    fingers = 4,
    direction = "right",
    action = function()
        hl.dispatch(hl.dsp.exec_cmd("~/.config/hypr/scripts/layout_navigate.sh focus_left"))
    end
})
