source = ~/.config/hypr/colors.conf

# Monitor
monitor=eDP-1, 1920x1080@144, 0x0, 1

# Apps
$terminal = kitty
$menu = wofi --show drun

# Keybinds
bind = SUPER, RETURN, exec, $terminal
bind = SUPER, D, exec, $menu
bind = SUPER, Q, killactive
bind = SUPER, B, exec, brave

# Workspaces
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7

# Move active window to a workspace with Super + Shift + [0-9]
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5
bind = SUPER SHIFT, 6, movetoworkspace, 6
bind = SUPER SHIFT, 7, movetoworkspace, 7

bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

# --- Window Navigation (Focus) ---
# Move focus with Super + Arrow keys
bind = SUPER, left,  movefocus, l
bind = SUPER, right, movefocus, r
bind = SUPER, up,    movefocus, u
bind = SUPER, down,  movefocus, d

# --- Window Manipulation (Move) ---
# physically swap window positions with Super + Shift + Arrow keys
bind = SUPER SHIFT, left,  movewindow, l
bind = SUPER SHIFT, right, movewindow, r
bind = SUPER SHIFT, up,    movewindow, u
bind = SUPER SHIFT, down,  movewindow, d

# Fullscreen
bind = SUPER, F, fullscreen

# Clipboard manager
bind = SUPER, V, exec, cliphist list | wofi --dmenu | cliphist decode | wl-copy

exec-once = waybar
exec-once = awww-daemon
exec-once = awww restore
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data

decoration {
    rounding = 10

    active_opacity = 1.0
    inactive_opacity = 0.95

    blur {
        enabled = true
        size = 6
        passes = 2
    }
}

animations {
    enabled = true

    bezier = myBezier, 0.05, 0.9, 0.1, 1.0

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%

    animation = fade, 1, 4, default
    animation = workspaces, 1, 5, default
}

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = $primary 
    col.inactive_border = $surface
}
