source = $HOME/.config/hypr/colors.conf

general {
    no_fade_in = false
    grace = 0
    disable_loading = true
}

background {
    monitor =
    path = screenshot
    color = $surface
    blur_passes = 2
    blur_size = 10
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.4
    vibrancy = 0.2
}

# --- TIME ---
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(255, 255, 255, 0.95)
    font_size = 90
    font_family = Geist Bold
    position = 0, 120
    halign = center
    valign = center
}

# --- DATE ---
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %B %d")"
    color = rgba(255, 255, 255, 0.7)
    font_size = 20
    font_family = Geist SemiBold
    position = 0, 40
    halign = center
    valign = center
}

# --- GREETING ---
label {
    monitor =
    text = Welcome Back, Masum
    color = rgba(255, 255, 255, 0.6)
    font_size = 14
    font_family = Geist SemiBold
    position = 0, -100
    halign = center
    valign = center
}

# --- INPUT FIELD ---
input-field {
    monitor =
    size = 240, 50
    outline_thickness = 2
    dots_size = 0.25 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.3 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    dots_rounding = -1 # -1 default circle, -2 follow input-field rounding
    outer_color = rgba(255, 255, 255, 0.1)
    inner_color = rgba(20, 20, 20, 0.6)
    font_color = rgb(230, 230, 230)
    fade_on_empty = false
    placeholder_text = <span foreground="##888888">Enter Password...</span>
    hide_input = false
    rounding = 14
    check_color = rgba(255, 255, 255, 0.4)
    fail_color = rgba(255, 85, 85, 0.8) # Red on failure
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    fail_transition = 200 # ms
    position = 0, -160
    halign = center
    valign = center
}

# --- LAYOUT / CAPS LOCK WARNING ---
label {
    monitor =
    text = cmd[update:1000] echo "$([ $(hyprctl devices -j | jq -r '.keyboards[] | select(.main == true) | .caps') = "true" ] && echo "󰪛 CAPS LOCK")"
    color = rgba(255, 85, 85, 0.9)
    font_size = 12
    font_family = Geist Bold
    position = 0, -225
    halign = center
    valign = center
}

# --- BATTERY ---
label {
    monitor =
    text = cmd[update:1000] echo "<span font_family='Symbols Nerd Font'>󰁹</span> $(cat /sys/class/power_supply/BAT1/capacity)%"
    color = rgba(255, 255, 255, 0.8)
    font_size = 20
    font_family = Geist
    position = -30, -30
    halign = right
    valign = top
}
