-- -----------------------------------------------------
-- HYPRLAND LUA CONFIGURATION (v0.55+)
-- -----------------------------------------------------
require("configs.env")
require("configs.monitors")
require("configs.settings")
require("configs.binds")
require("configs.autostart")

require("configs.colors")

hl.config({
    autogenerated = false
})


