-- -----------------------------------------------------
-- HYPRLAND LUA CONFIGURATION (v0.55+)
-- -----------------------------------------------------
require("configs.colors") -- Load colors first for dynamic rules
require("configs.env")
require("configs.monitors")
require("configs.settings")
require("configs.binds")
require("configs.autostart")

hl.config({
    autogenerated = false
})

-- -----------------------------------------------------
-- NATIVE GESTURES (v0.55.0 Lua Syntax)
-- -----------------------------------------------------
hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })

-- -----------------------------------------------------
-- PERSISTENT WORKSPACES (Delayed Bridge)
-- -----------------------------------------------------
hl.timer(function()
    for i = 1, 5 do
        hl.keyword("workspace", i .. ",monitor:eDP-1,persistent:true")
    end
end, { timeout = 1000, type = "oneshot" })
