# Monitor
monitor=,preferred,auto,1

# Apps
$terminal = kitty
$menu = rofi -show drun

# Keybinds
bind = SUPER, RETURN, exec, $terminal
bind = SUPER, D, exec, $menu
bind = SUPER, Q, killactive

# Workspaces
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5

# Fullscreen
bind = SUPER, F, fullscreen

# Floating toggle
bind = SUPER, V, togglefloating

exec-once = waybar
exec-once = swww-daemon

decoration {
    rounding = 10

    active_opacity = 1.0
    inactive_opacity = 0.95

    blur {
        enabled = true
        size = 6
        passes = 2
    }
}

animations {
    enabled = true

    bezier = myBezier, 0.05, 0.9, 0.1, 1.0

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%

    animation = fade, 1, 4, default
    animation = workspaces, 1, 5, default
}
