general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "on" })'
}

# --- DIM SCREEN (5 Mins) ---
listener {
    timeout = 300
    on-timeout = brightnessctl -s set 10%
    on-resume = brightnessctl -r
}

# --- LOCK SESSION (6 Mins) ---
listener {
    timeout = 360
    on-timeout = loginctl lock-session
}

# --- TURN OFF DISPLAY (7 Mins) ---
listener {
    timeout = 420
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "off" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "on" })'
}

# --- SUSPEND (10 Mins) ---
listener {
    timeout = 600
    on-timeout = systemctl suspend
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "on" })' && brightnessctl -r
}
