# Navigation & Menus
tab           script-binding uosc/toggle-ui
menu          script-binding uosc/menu
mbtn_right    script-binding uosc/menu
s             script-binding uosc/subtitles
a             script-binding uosc/audio
c             script-binding uosc/chapters
p             script-binding uosc/items
o             script-binding uosc/open-file

# Seeking & Volume
SPACE         cycle pause; script-binding uosc/flash-pause-indicator
RIGHT         seek  5
LEFT          seek -5
Shift+RIGHT   seek  10
Shift+LEFT    seek -10
Ctrl+RIGHT    seek  30
Ctrl+LEFT     seek -30
Alt+RIGHT     seek  1
Alt+LEFT      seek -1
UP            no-osd add volume  2; script-binding uosc/flash-volume
DOWN          no-osd add volume -2; script-binding uosc/flash-volume
WHEEL_UP      no-osd add volume  2; script-binding uosc/flash-volume
WHEEL_DOWN    no-osd add volume -2; script-binding uosc/flash-volume

# Playback Speed
]             add speed 0.1; script-binding uosc/flash-speed
[             add speed -0.1; script-binding uosc/flash-speed
\             set speed 1.0; script-binding uosc/flash-speed

# Window
f             cycle fullscreen
ESC           set fullscreen no
q             quit
