# Monitor
monitor=,preferred,auto,1

# Apps
$terminal = kitty
$menu = rofi -show drun

# Keybinds
bind = SUPER, RETURN, exec, $terminal
bind = SUPER, D, exec, $menu
bind = SUPER, Q, killactive

# Workspaces
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3

# Fullscreen
bind = SUPER, F, fullscreen

# Floating toggle
bind = SUPER, V, togglefloating

exec-once = waybar
exec-once = swww-daemon
