[main]
font=Geist:weight=bold:size=8
prompt="❯ "
icon-theme=Papirus
width=40
lines=10
horizontal-pad=15
vertical-pad=10
inner-pad=8
line-height=20
letter-spacing=0.5
border-radius=12
border-width=0

[colors]
# The main text color (Apps and list items)
text={{colors.on_surface.default.hex}}ff

# The color of the '❯' prompt specifically
prompt={{colors.primary.default.hex}}ff

# The color of the characters you have typed (Searching)
input={{colors.on_surface.default.hex}}ff

# The color of the matched characters in the list
match={{colors.primary.default.hex}}ff

# Selection colors (When you hover/highlight an item)
selection={{colors.primary.default.hex}}44
selection-text={{colors.primary.default.hex}}ff
selection-match={{colors.primary.default.hex}}ff

background={{colors.surface.default.hex}}dd
border=00000000

[border]
width=0
radius=12
