# Timeline style
timeline_style=line
timeline_line_width=4
timeline_size=40
timeline_border=1
timeline_persistency=paused

# Controls & UI Elements
controls=play_pause,menu,subtitles,audio,video,playlist,fullscreen
controls_size=32
controls_margin=18
controls_spacing=12

# Typography
font=Geist Medium

# Volume control
volume_size=40
volume_border=1

# Appearance & animations
animation_duration=150
click_threshold=0
buffered_time_threshold=10

# Opacity (Crisp readable submenus)
opacity=submenu=0.85,menu=1,curtain=0.85

# Matugen Dynamic Colors
color=foreground={{colors.primary.default.hex_stripped}},foreground_text={{colors.on_primary.default.hex_stripped}},background={{colors.surface.default.hex_stripped}},background_text={{colors.on_surface.default.hex_stripped}},curtain={{colors.surface_container_lowest.default.hex_stripped}},success={{colors.primary.default.hex_stripped}},error={{colors.error.default.hex_stripped}}
