timeline_style=line
timeline_line_width=4
timeline_size=40
timeline_border=1
timeline_persistency=paused

controls=play_pause,menu,subtitles,audio,video,playlist,fullscreen
controls_size=32
controls_margin=18
controls_spacing=12

font=Geist Medium

volume_size=40
volume_border=1

animation_duration=150
click_threshold=0
buffered_time_threshold=10

opacity=submenu=0.85,menu=1,curtain=0.85

color=foreground=b5c9db,foreground_text=1f3241,background=131314,background_text=e4e2e3,curtain=0d0e0f,success=b5c9db,error=ffb4ab
