timeline_style=line
timeline_line_width=4
timeline_size=40
timeline_border=1
timeline_persistency=paused

controls=play_pause,menu,subtitles,audio,video,playlist,fullscreen
controls_size=32
controls_margin=18
controls_spacing=12

font=Geist Medium

volume_size=40
volume_border=1

animation_duration=150
click_threshold=0
buffered_time_threshold=10

opacity=submenu=0.85,menu=1,curtain=0.85

color=foreground=d9b9ff,foreground_text=460085,background=16121a,background_text=e9dfec,curtain=100d15,success=d9b9ff,error=ffb4ab
