-- -----------------------------------------------------
-- DYNAMIC COLORS (Generated by Matugen)
-- -----------------------------------------------------

_G.color_primary = "#69d8cf"
_G.color_primary_rgba = "rgba(69d8cf, 0.1)"
_G.color_surface = "#0f1414"

return true
