-- -----------------------------------------------------
-- DYNAMIC COLORS (Generated by Matugen)
-- -----------------------------------------------------

_G.color_primary = "#c0c5e0"
_G.color_primary_rgba = "rgba(c0c5e0, 0.1)"
_G.color_surface = "#131315"

return true
