-- -----------------------------------------------------
-- DYNAMIC COLORS (Generated by Matugen)
-- -----------------------------------------------------

_G.color_primary = "#d9b9ff"
_G.color_primary_rgba = "rgba(d9b9ff, 0.1)"
_G.color_surface = "#16121a"

return true
